export const perpEngineAbi = [
  { type: "error", name: "InsufficientMargin", inputs: [] },
  { type: "error", name: "ExcessiveLeverage", inputs: [] },
  { type: "error", name: "PositionExists", inputs: [] },
  { type: "error", name: "StaleOracle", inputs: [] },
  { type: "error", name: "PriceNotSet", inputs: [] },
  { type: "error", name: "MarketNotActive", inputs: [] },
  { type: "error", name: "OpenInterestExceeded", inputs: [] },
  { type: "error", name: "NotLiquidatable", inputs: [] },
  { type: "error", name: "NoPosition", inputs: [] },
  { type: "error", name: "TransferFailed", inputs: [] },
  { type: "error", name: "PausedError", inputs: [] },
  {
    type: "function",
    name: "setMarkPrices",
    inputs: [
      { name: "tickers", type: "string[]" },
      { name: "markPrices", type: "uint64[]" },
      { name: "indexPrices", type: "uint64[]" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "openPosition",
    inputs: [
      { name: "ticker", type: "string" },
      { name: "isLong", type: "bool" },
      { name: "marginAmount", type: "uint256" },
      { name: "sizeShares", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "closePosition",
    inputs: [
      { name: "ticker", type: "string" },
      { name: "sizeShares", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "addMargin",
    inputs: [
      { name: "ticker", type: "string" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "liquidate",
    inputs: [
      { name: "user", type: "address" },
      { name: "ticker", type: "string" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getPosition",
    inputs: [
      { name: "user", type: "address" },
      { name: "ticker", type: "string" },
    ],
    outputs: [
      { name: "side", type: "uint8" },
      { name: "size", type: "uint256" },
      { name: "margin", type: "uint256" },
      { name: "entryPrice", type: "uint256" },
      { name: "unrealizedPnl", type: "int256" },
      { name: "equity", type: "int256" },
      { name: "liquidationPrice", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "markets",
    inputs: [{ name: "tickerHash", type: "bytes32" }],
    outputs: [
      { name: "active", type: "bool" },
      { name: "markPrice", type: "uint64" },
      { name: "indexPrice", type: "uint64" },
      { name: "lastMarkUpdate", type: "uint64" },
      { name: "maxLeverage", type: "uint16" },
      { name: "maintenanceMarginBps", type: "uint16" },
      { name: "maxOpenInterestUsd", type: "uint64" },
      { name: "fundingRateBps", type: "int32" },
      { name: "cumulativeFundingIndex", type: "uint128" },
      { name: "lastFundingTime", type: "uint64" },
      { name: "longOpenInterestShares", type: "uint128" },
      { name: "shortOpenInterestShares", type: "uint128" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "applyFunding",
    inputs: [{ name: "ticker", type: "string" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "poolBalance",
    inputs: [],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "insuranceFund",
    inputs: [],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "paused",
    inputs: [],
    outputs: [{ type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "PositionOpened",
    inputs: [
      { indexed: true, name: "user", type: "address" },
      { indexed: true, name: "ticker", type: "bytes32" },
      { indexed: false, name: "side", type: "uint8" },
      { indexed: false, name: "size", type: "uint256" },
      { indexed: false, name: "margin", type: "uint256" },
      { indexed: false, name: "entryPrice", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "PositionClosed",
    inputs: [
      { indexed: true, name: "user", type: "address" },
      { indexed: true, name: "ticker", type: "bytes32" },
      { indexed: false, name: "side", type: "uint8" },
      { indexed: false, name: "sizeClosed", type: "uint256" },
      { indexed: false, name: "realizedPnl", type: "int256" },
      { indexed: false, name: "marginReturned", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "Liquidated",
    inputs: [
      { indexed: true, name: "user", type: "address" },
      { indexed: true, name: "liquidator", type: "address" },
      { indexed: true, name: "ticker", type: "bytes32" },
      { indexed: false, name: "size", type: "uint256" },
      { indexed: false, name: "pnl", type: "int256" },
      { indexed: false, name: "liquidatorBonus", type: "uint256" },
    ],
  },
] as const;

export const perpEngineEventsAbi = [
  {
    type: "event",
    name: "PositionOpened",
    inputs: [
      { indexed: true, name: "user", type: "address" },
      { indexed: true, name: "ticker", type: "bytes32" },
      { indexed: false, name: "side", type: "uint8" },
      { indexed: false, name: "size", type: "uint256" },
      { indexed: false, name: "margin", type: "uint256" },
      { indexed: false, name: "entryPrice", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "PositionClosed",
    inputs: [
      { indexed: true, name: "user", type: "address" },
      { indexed: true, name: "ticker", type: "bytes32" },
      { indexed: false, name: "side", type: "uint8" },
      { indexed: false, name: "sizeClosed", type: "uint256" },
      { indexed: false, name: "realizedPnl", type: "int256" },
      { indexed: false, name: "marginReturned", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "Liquidated",
    inputs: [
      { indexed: true, name: "user", type: "address" },
      { indexed: true, name: "liquidator", type: "address" },
      { indexed: true, name: "ticker", type: "bytes32" },
      { indexed: false, name: "size", type: "uint256" },
      { indexed: false, name: "pnl", type: "int256" },
      { indexed: false, name: "liquidatorBonus", type: "uint256" },
    ],
  },
] as const;

export function getPerpContractAbi() {
  return perpEngineAbi;
}
